### ISSUE TITLE
Collisions without MoveAndSlide

### ISSUE THREAD

**Issue by lorenzo-arena** [lawnjelly/godot-snapping-demo#1]
Hi; I don't know if this is the best way to contact you however I have a question on rule 4: how would I go about detecting collisions if not using the physics engine? For example with Kinematic/Character bodies isn't it mandatory to use the `MoveAndSlide` method to be able to detect collisions? Are there other ways?

**Comment by lawnjelly** [comment]
If you aren't using the physics engine, and are doing collision detection yourself, you don't need to use Kinematic/Character bodies, and indeed should not.

Typical ways of doing pixel 2d collision detection take advantage of the speed of pixel operations, but this very much depends whether you are doing this in gdscript (which may be slow for per pixel) versus c++ or maybe c#.

For a fast approach in gdscript if you can't use pixel operations, I would maybe have a set of collision tiles with various combinations, such as hard edge on the left or right, diagonal to the left or right etc. Then you can calculate the response of a "player" according to whereabouts it is within the collision tile.

For pixel based approaches, you would typically have a collision pixel map (maybe just 1 bit, black and white, white being solid, black being non-solid) then either:
* Sample out from the player the collision map maybe using 3 pixel probes if moving e.g. right
* or do a bitwise AND of the values from your sprite against the background.
If the result is more than zero, you have a collision and you can't make the move. This depends on you being familiar with bitwise operations, and using a language that supports them. Bitwise operations are low level instructions that run very fast on the CPU (it can collide detect 2 32 bit fields against each other in the same time or less than an addition).
https://en.wikipedia.org/wiki/Bitwise_operation

It would be nice to write a module, or even have something in Godot core to do this kind of thing, but it may be considered a bit too niche, and difficult to come up with a generalized user friendly solution. Is on my todo list (if I ever get time).

**Comment by lorenzo-arena** [comment]
> Typical ways of doing pixel 2d collision detection take advantage of the speed of pixel operations, but this very much depends whether you are doing this in gdscript (which may be slow for per pixel) versus c++ or maybe c#.

I'm currently scripting everything in C#, as it's a language I already knew and I like having type checks at compile time.

As for the collision detection implementation I have experience with bitwise operations as I'm a firmware developer by day 😃 So if I'm understanding correctly there should be a "new" collision node which implements this kind of logic? Or there should be a more "global" script which check for collisions across the entire scene?

> It would be nice to write a module, or even have something in Godot core to do this kind of thing

Actually I expected that since a lot of indie use pixel art; at this point maybe pixel *perfect* pixel art is not very much used? I came into this hoping to be able to replicate pixel perfection as seen in games like Hyper Light Drifter but I didn't expect it to be this hard.

On a side note, one of the mechanism which I tried was to have a viewport set to the pixel art canvas size (e.g. 480x270), then scale the viewport container to reach a high resolution (like 1920x1080). This works, however as always using methods like `MoveAndSlide` moves the sprites into subpixel positions which creates strange artifacts. What I was thinking of as an approach was to have a "hidden" float position parameter which should track the position in the physics engine, and then rendering it by rounding to the nearest pixel perfect position. If I'm understanding correctly this should be done in Godot 4 (don't know if it's been ported to 3.x as well) using the snap options, with which transform positions should be snapped to the nearest pixel on the grid. However it's seems to be currently bugged: https://github.com/godotengine/godot/issues/66527

**Comment by lawnjelly** [comment]
> What I was thinking of as an approach was to have a "hidden" float position parameter which should track the position in the physics engine, and then rendering it by rounding to the nearest pixel perfect position.

Yes, if you really want to use the physics engine, you can maybe make a physics node, then have a sprite as child, but call `set_as_toplevel()` in the `_ready()` of the sprite (so it doesn't inherit the parent transform), and set the global transform directly on each frame to a quantized version of the parent global_transform.

However, if you use the physics engine although you can get pixel perfect visuals, the experience may not be so good as you are liable to get aliasing stutter as the physics movement is unlikely to coincide with regular pixel movement.

> So if I'm understanding correctly there should be a "new" collision node which implements this kind of logic? Or there should be a more "global" script which check for collisions across the entire scene?

It's totally up to you, that is your job as game developer! :slightly_smiling_face:
It depends how you want your game to work, the game design details, and what would be easiest for you etc.

> If I'm understanding correctly this should be done in Godot 4 (don't know if it's been ported to 3.x as well)

I spent some time experimenting with core snapping in 3.x last year, but it proved very difficult because most users don't understand snapping and expected it to solve problems it cannot. For this reason we reverted the snapping in 3.x for the time being.

I may have to revisit it during implementation of core 2D fixed timestep interpolation, because snapping has to be done _after_ fixed timestep interpolation, so can't easily be customized by the user (unless we use a callback which would be inefficient).

**Comment by lorenzo-arena** [comment]
> However, if you use the physics engine although you can get pixel perfect visuals, the experience may not be so good as you are liable to get aliasing stutter as the physics movement is unlikely to coincide with regular pixel movement.

I gave it a quick try and I think there is noticeable stutter yes.

> I spent some time experimenting with core snapping in 3.x last year, but it proved very difficult because most users don't understand snapping and expected it to solve problems it cannot.

But would you say that it should be the right tool for this job? Or still the best way would be to have a custom collision detection engine?

**Comment by lawnjelly** [comment]
> But would you say that it should be the right tool for this job? Or still the best way would be to have a custom collision detection engine?

These are two different things. You can have snapping with or without pixel collision detection, and you can have pixel collision detection with or without snapping.

Imo for pixel retro games, my preferred combination for smooth movement is probably snapping + pixel collision detection. But bear in mind there is no perfect solution because monitors don't all refresh at e.g. 60hz (so even if you get it looking right on your development rig, someone with different refresh rate may see stutter).

Even with pixel movement per frame, you have to either live with aliasing jitter or vary the speed of movement on different monitors. Pick your poison.

**Comment by lorenzo-arena** [comment]
Thanks! I have a lot more clues about dealing with pixel perfect games now
